version: "3"
services:
  app:
    container_name: tickema-next-app
    build:
      context: ./app
      dockerfile: dev.Dockerfile
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    restart: always
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    container_name: tickema-next-db
    image: mysql:latest
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./app/.env
    ports:
      - "3306:3306"

volumes:
  node_modules:
  db_data:
